export const myPeople = [
  {
    firstName: "Philip",
    lastName: "Aff",
    birthMonth: "December",
    birthDay: 26,
    birthYear: 1965,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Lauren",
    lastName: "At",
    birthMonth: "March",
    birthDay: 1,
    birthYear: 1975,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Paulette",
    lastName: "B.",
    birthMonth: "March",
    birthDay: 28,
    birthYear: null,
    passedAway: "3/10/23",
    comment: "❤️",
    groups: ["Pet"],
  },
  {
    firstName: "James",
    lastName: "B.",
    birthMonth: "November",
    birthDay: 13,
    birthYear: null,
    passedAway: "6/13/11",
    comment: "❤️",
    groups: ["Pet"],
  },
  {
    firstName: "Sue",
    lastName: "Bl",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Chris",
    lastName: "Bo",
    birthMonth: "September",
    birthDay: 2,
    birthYear: 1969,
    passedAway: null,
    comment: "I take it you and your wife are still alive?",
    groups: ["unknown"],
  },
  {
    firstName: "Anne",
    lastName: "Br",
    birthMonth: "December",
    birthDay: 15,
    birthYear: 1973,
    passedAway: null,
    comment: "Carolyn's friend, loco?",
    groups: ["unknown"],
  },
  {
    firstName: "Ruth",
    lastName: "Ch",
    birthMonth: "September",
    birthDay: 8,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Leah",
    lastName: "Cop",
    birthMonth: "October",
    birthDay: 3,
    birthYear: 1970,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Robert",
    lastName: "Cou",
    birthMonth: "July",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "James",
    lastName: "Cur.",
    birthMonth: "January",
    birthDay: 3,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Helena",
    lastName: "Da.",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Anne",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 13,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "George",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 17,
    birthYear: 1941,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Diane",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 21,
    birthYear: 1942,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Pat",
    lastName: "DeP.",
    birthMonth: "December",
    birthDay: 25,
    birthYear: 1974,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Leigh",
    lastName: "Fe.",
    birthMonth: "November",
    birthDay: 21,
    birthYear: 1977,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Maurice",
    lastName: "Fon.",
    birthMonth: "March",
    birthDay: 21,
    birthYear: null,
    passedAway: null,
    comment: "Flick",
    groups: ["unknown"],
  },
  {
    firstName: "Rita",
    lastName: "Hen.",
    birthMonth: "July",
    birthDay: 28,
    birthYear: 1919,
    passedAway: "September 5, 2012",
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Pat",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 25,
    birthYear: 1981,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Mike",
    lastName: "Hen.",
    birthMonth: "March",
    birthDay: 9,
    birthYear: 1984,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Jack",
    lastName: "Hen.",
    birthMonth: "April",
    birthDay: 14,
    birthYear: 1987,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Daniel",
    lastName: "Hen.",
    birthMonth: "July",
    birthDay: 27,
    birthYear: 1988,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Marty",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 2,
    birthYear: 1948,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Maureen",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 18,
    birthYear: 1956,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Tricia",
    lastName: "Hen.",
    birthMonth: "July",
    birthDay: 22,
    birthYear: 1983,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Cathy",
    lastName: "H.",
    birthMonth: "December",
    birthDay: 15,
    birthYear: 1953,
    passedAway: null,
    comment: null,
    groups: ["Friend"],
  },
  {
    firstName: "Rich",
    lastName: "H.",
    birthMonth: "August",
    birthDay: 26,
    birthYear: 1949,
    passedAway: null,
    comment: null,
    groups: ["Friend"],
  },
  {
    firstName: "Kathy",
    lastName: "Ho.",
    birthMonth: "November",
    birthDay: 28,
    birthYear: null,
    passedAway: null,
    comment: "Bergen Catholic",
    groups: ["unknown"],
  },
  {
    firstName: "Aunt Peggy",
    lastName: "Hov.",
    birthMonth: "May",
    birthDay: 22,
    birthYear: 1927,
    passedAway: "September 24, 2012",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Uncle Warren",
    lastName: "Hov.",
    birthMonth: "November",
    birthDay: 25,
    birthYear: 1921,
    passedAway: "February 23, 2009",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Karen",
    lastName: "Hov.",
    birthMonth: "May",
    birthDay: 9,
    birthYear: 1957,
    passedAway: null,
    comment: "Cousin",
    groups: ["Hovsepian"],
  },
  {
    firstName: "Janice",
    lastName: "Hov.",
    birthMonth: "April",
    birthDay: 2,
    birthYear: 1961,
    passedAway: null,
    comment: "Cousin",
    groups: ["Hovsepian"],
  },
  {
    firstName: "Rich",
    lastName: "Hov.",
    birthMonth: "March",
    birthDay: 22,
    birthYear: 1953,
    passedAway: null,
    comment: "Cousin",
    groups: ["Hovsepian"],
  },
  {
    firstName: "Carolyn",
    lastName: "Hov.",
    birthMonth: "July",
    birthDay: 2,
    birthYear: 1954,
    passedAway: null,
    comment: "Cousin",
    groups: ["Hovsepian"],
  },
  {
    firstName: "TBD",
    lastName: "Hov.",
    birthMonth: "December",
    birthDay: 30,
    birthYear: 1980,
    passedAway: null,
    comment: "Rich's son",
    groups: ["Hovsepian"],
  },
  {
    firstName: "Aunt Rose",
    lastName: "I.",
    birthMonth: "August",
    birthDay: 13,
    birthYear: 1923,
    passedAway: "May 20, 2021",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Uncle Mike",
    lastName: "I.",
    birthMonth: "November",
    birthDay: 19,
    birthYear: 1925,
    passedAway: "January 20, 2012",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Michael",
    lastName: "I.",
    birthMonth: "May",
    birthDay: 26,
    birthYear: 1952,
    passedAway: null,
    comment: "Me",
    groups: ["Immediate"],
  },
  {
    firstName: "Susan",
    lastName: "I.",
    birthMonth: "May",
    birthDay: 15,
    birthYear: 1954,
    passedAway: null,
    comment: "Wife",
    groups: ["Immediate"],
  },
  {
    firstName: "Jennifer",
    lastName: "I.",
    birthMonth: "January",
    birthDay: 22,
    birthYear: 1980,
    passedAway: null,
    comment: "Daughter",
    groups: ["Immediate"],
  },
  {
    firstName: "Jessica",
    lastName: "I.",
    birthMonth: "August",
    birthDay: 24,
    birthYear: 1982,
    passedAway: null,
    comment: "Daughter",
    groups: ["Immediate"],
  },
  {
    firstName: "Crosby",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 1,
    birthYear: 2011,
    passedAway: null,
    comment: "Dog",
    groups: ["Pet"],
  },
  {
    firstName: "Jason",
    lastName: "J.",
    birthMonth: "July",
    birthDay: 24,
    birthYear: 1978,
    passedAway: null,
    comment: "Son-in-law",
    groups: ["Immediate"],
  },
  {
    firstName: "Leo",
    lastName: "J.",
    birthMonth: "February",
    birthDay: 2,
    birthYear: 2014,
    passedAway: null,
    comment: "Grandson",
    groups: ["Immediate", "Grandkids"],
  },
  {
    firstName: "Milo",
    lastName: "J.",
    birthMonth: "April",
    birthDay: 23,
    birthYear: 2016,
    passedAway: null,
    comment: "Grandson",
    groups: ["Immediate", "Grandkids"],
  },
  {
    firstName: "Arlo",
    lastName: "J.",
    birthMonth: "August",
    birthDay: 28,
    birthYear: 2018,
    passedAway: null,
    comment: "Grandson",
    groups: ["Immediate", "Grandkids"],
  },
  {
    firstName: "Rich",
    lastName: "Ke.",
    birthMonth: "May",
    birthDay: 27,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["unknown"],
  },
  {
    firstName: "Kevin",
    lastName: "Ki.",
    birthMonth: "August",
    birthDay: 16,
    birthYear: 1983,
    passedAway: null,
    comment: "Son-in-law",
    groups: ["Immediate"],
  },
  {
    firstName: "TBD",
    lastName: "Ki.",
    birthMonth: "July",
    birthDay: 23,
    birthYear: 2013,
    passedAway: null,
    comment: "Grandson",
    groups: ["Immediate", "Grandkids"],
  },
  {
    firstName: "TBD",
    lastName: "Ki.",
    birthMonth: "November",
    birthDay: 14,
    birthYear: 2015,
    passedAway: null,
    comment: "Grandson",
    groups: ["Immediate", "Grandkids"],
  },
  {
    firstName: "Liza",
    lastName: "Kn.",
    birthMonth: "February",
    birthDay: 23,
    birthYear: null,
    passedAway: null,
    comment: "Book club",
    groups: ["Friend"],
  },
  {
    firstName: "Bob",
    lastName: "Ko.",
    birthMonth: "March",
    birthDay: 21,
    birthYear: null,
    passedAway: null,
    comment: "Flick",
    groups: ["Friend"],
  },
  {
    firstName: "Aunt Anne",
    lastName: "L.",
    birthMonth: "December",
    birthDay: 19,
    birthYear: 1920,
    passedAway: "June 25, 2011",
    comment: "❤️",
    groups: ["Deceased"],
  },
  {
    firstName: "Aunt Terry",
    lastName: "L.",
    birthMonth: "October",
    birthDay: 4,
    birthYear: 1928,
    passedAway: "May 2, 2020",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Uncle Dominick",
    lastName: "L.",
    birthMonth: "November",
    birthDay: 1,
    birthYear: 1923,
    passedAway: "December 6, 2015",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Michael",
    lastName: "L.",
    birthMonth: "November",
    birthDay: 26,
    birthYear: 1948,
    passedAway: null,
    comment: "Cousin",
    groups: ["Loiacono"],
  },
  {
    firstName: "Laura",
    lastName: "L.",
    birthMonth: "September",
    birthDay: 21,
    birthYear: 1957,
    passedAway: null,
    comment: "Cousin",
    groups: ["Loiacono"],
  },
  {
    firstName: "Andrew",
    lastName: "L.",
    birthMonth: "April",
    birthDay: 27,
    birthYear: 1991,
    passedAway: null,
    comment: "Cousin's son",
    groups: ["Loiacono"],
  },
  {
    firstName: "Gregory",
    lastName: "L.",
    birthMonth: "August",
    birthDay: 26,
    birthYear: 1994,
    passedAway: null,
    comment: "Cousin's son",
    groups: ["Loiacono"],
  },
  {
    firstName: "Stephen",
    lastName: "L.",
    birthMonth: "May",
    birthDay: 2,
    birthYear: 1957,
    passedAway: null,
    comment: "Cousin",
    groups: ["Loiacono"],
  },
  {
    firstName: "TBD",
    lastName: "L.",
    birthMonth: "August",
    birthDay: 27,
    birthYear: 1991,
    passedAway: null,
    comment: "Cousin's son",
    groups: ["Loiacono"],
  },
  {
    firstName: "TBD",
    lastName: "L.",
    birthMonth: "November",
    birthDay: 25,
    birthYear: 1993,
    passedAway: null,
    comment: "Cousin's son",
    groups: ["Loiacono"],
  },
  {
    firstName: "Joanne",
    lastName: "L.",
    birthMonth: "July",
    birthDay: 20,
    birthYear: 1961,
    passedAway: null,
    comment: "Cousin",
    groups: ["Loiacono"],
  },
  {
    firstName: "Kenny",
    lastName: "L.",
    birthMonth: "July",
    birthDay: 19,
    birthYear: 1988,
    passedAway: null,
    comment: "Cousin's son",
    groups: ["Loiacono"],
  },
  {
    firstName: "Michelle",
    lastName: "L.",
    birthMonth: "February",
    birthDay: 16,
    birthYear: 1991,
    passedAway: null,
    comment: "Cousin's daughter",
    groups: ["Loiacono"],
  },
  {
    firstName: "Mom",
    lastName: "L.",
    birthMonth: "September",
    birthDay: 18,
    birthYear: 1926,
    passedAway: "November 2, 2021",
    comment: "Best mom ever",
    groups: ["Deceased"],
  },
  {
    firstName: "Dad",
    lastName: "L.",
    birthMonth: "October",
    birthDay: 30,
    birthYear: 1924,
    passedAway: "November 21, 2004",
    comment: "Best dad ever",
    groups: ["Deceased"],
  },
  {
    firstName: "Dominick",
    lastName: "L.",
    birthMonth: "October",
    birthDay: 2,
    birthYear: 1953,
    passedAway: null,
    comment: "Brother",
    groups: ["Immediate"],
  },
  {
    firstName: "Kathy",
    lastName: "L.",
    birthMonth: "April",
    birthDay: 26,
    birthYear: 1954,
    passedAway: null,
    comment: "Sister-in-law",
    groups: ["Immediate"],
  },
  {
    firstName: "Michael",
    lastName: "L.",
    birthMonth: "January",
    birthDay: 14,
    birthYear: 1983,
    passedAway: null,
    comment: "Nephew",
    groups: ["Immediate"],
  },
  {
    firstName: "Stephen",
    lastName: "L.",
    birthMonth: "December",
    birthDay: 28,
    birthYear: 1985,
    passedAway: null,
    comment: "Nephew",
    groups: ["Immediate"],
  },
  {
    firstName: "Laura",
    lastName: "M.",
    birthMonth: "May",
    birthDay: 16,
    birthYear: 1982,
    passedAway: null,
    comment: null,
    groups: ["Friend"],
  },
  {
    firstName: "Liz",
    lastName: "Ma.",
    birthMonth: "January",
    birthDay: 23,
    birthYear: null,
    passedAway: null,
    comment: "Book club",
    groups: ["Friend"],
  },
  {
    firstName: "Aunt Gloria",
    lastName: "Mo.",
    birthMonth: "May",
    birthDay: 2,
    birthYear: 1931,
    passedAway: "March 11, 2016",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Uncle Frank",
    lastName: "Mo.",
    birthMonth: "August",
    birthDay: 21,
    birthYear: 1928,
    passedAway: "May 25, 2021",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Gary",
    lastName: "Mo.",
    birthMonth: "September",
    birthDay: 17,
    birthYear: 1955,
    passedAway: null,
    comment: "Cousin",
    groups: ["Montalbano"],
  },
  {
    firstName: "Frank",
    lastName: "Mo.",
    birthMonth: "November",
    birthDay: 15,
    birthYear: 1958,
    passedAway: null,
    comment: "Cousin",
    groups: ["Montalbano"],
  },
  {
    firstName: "Ronnie",
    lastName: "Mo.",
    birthMonth: "May",
    birthDay: 13,
    birthYear: 1961,
    passedAway: null,
    comment: "Cousin",
    groups: ["Montalbano"],
  },
  {
    firstName: "TBD",
    lastName: "Mo.",
    birthMonth: "February",
    birthDay: 19,
    birthYear: 1988,
    passedAway: null,
    comment: "Gary's Son",
    groups: ["Montalbano"],
  },
  {
    firstName: "TBD",
    lastName: "Mo.",
    birthMonth: "May",
    birthDay: 13,
    birthYear: 1991,
    passedAway: null,
    comment: "Gary's Son",
    groups: ["Montalbano"],
  },
  {
    firstName: "TBD",
    lastName: "Mo.",
    birthMonth: "April",
    birthDay: 2,
    birthYear: 1991,
    passedAway: null,
    comment: "Frank's Daughter",
    groups: ["Montalbano"],
  },
  {
    firstName: "TBD",
    lastName: "Mo.",
    birthMonth: "November",
    birthDay: 15,
    birthYear: 1993,
    passedAway: null,
    comment: "Frank's Son",
    groups: ["Montalbano"],
  },
  {
    firstName: "Nana",
    lastName: "Mon.",
    birthMonth: "January",
    birthDay: 1,
    birthYear: 1900,
    passedAway: "8/9/69",
    comment: "Grandmother",
    groups: ["Deceased"],
  },
  {
    firstName: "Grandpa",
    lastName: "Mon.",
    birthMonth: "January",
    birthDay: 1,
    birthYear: 1900,
    passedAway: "8/9/69",
    comment: "Grandfather",
    groups: ["Deceased"],
  },
  {
    firstName: "TBD",
    lastName: "N.",
    birthMonth: "August",
    birthDay: 30,
    birthYear: 2023,
    passedAway: null,
    comment: "Daniel's Kid",
    groups: ["Friend"],
  },
  {
    firstName: "Barbara",
    lastName: "Ne.",
    birthMonth: "November",
    birthDay: 28,
    birthYear: 1951,
    passedAway: null,
    comment: null,
    groups: ["Friend"],
  },
  {
    firstName: "Rich",
    lastName: "O.",
    birthMonth: "November",
    birthDay: 23,
    birthYear: 1947,
    passedAway: null,
    comment: null,
    groups: ["Friend"],
  },
  {
    firstName: "Chris",
    lastName: "O.",
    birthMonth: "November",
    birthDay: 20,
    birthYear: 1970,
    passedAway: null,
    comment: null,
    groups: ["Friend"],
  },
  {
    firstName: "Keith",
    lastName: "O.",
    birthMonth: "May",
    birthDay: 30,
    birthYear: 1974,
    passedAway: null,
    comment: null,
    groups: ["Friend"],
  },
  {
    firstName: "Aunt Mary",
    lastName: "P.",
    birthMonth: "May",
    birthDay: 1,
    birthYear: 1930,
    passedAway: "1/12/16",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Uncle Frank",
    lastName: "P.",
    birthMonth: "November",
    birthDay: 20,
    birthYear: 1927,
    passedAway: "11/4/2014",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Frank",
    lastName: "P.",
    birthMonth: "August",
    birthDay: 1,
    birthYear: 1952,
    passedAway: "8/11/2008",
    comment: "Cousin",
    groups: ["Deceased"],
  },
  {
    firstName: "Joanne",
    lastName: "P.",
    birthMonth: "May",
    birthDay: 10,
    birthYear: 1954,
    passedAway: null,
    comment: "Cousin",
    groups: ["Paladino"],
  },
  {
    firstName: "Donna",
    lastName: "P.",
    birthMonth: "May",
    birthDay: 12,
    birthYear: 1955,
    passedAway: null,
    comment: "Cousin",
    groups: ["Paladino"],
  },
  {
    firstName: "Livia",
    lastName: "P.",
    birthMonth: "October",
    birthDay: 21,
    birthYear: 1981,
    passedAway: null,
    comment: "Cousin's daughter",
    groups: ["Paladino"],
  },
  {
    firstName: "Selena",
    lastName: "P.",
    birthMonth: "February",
    birthDay: 14,
    birthYear: 1984,
    passedAway: null,
    comment: "Cousin's daughter",
    groups: ["Paladino"],
  },
  {
    firstName: "William",
    lastName: "Pe.",
    birthMonth: "October",
    birthDay: 27,
    birthYear: 1951,
    passedAway: "October 27, 2022",
    comment: "The Good William",
    groups: ["Deceased"],
  },
  {
    firstName: "Betty",
    lastName: "Po.",
    birthMonth: "February",
    birthDay: 1,
    birthYear: null,
    passedAway: null,
    comment: "Book club",
    groups: ["Friend"],
  },
  {
    firstName: "Aunt Ann",
    lastName: "S.",
    birthMonth: "November",
    birthDay: 21,
    birthYear: 1921,
    passedAway: "December 2, 2008",
    comment: null,
    groups: ["Deceased"],
  },
  {
    firstName: "Sue",
    lastName: "Sc.",
    birthMonth: "February",
    birthDay: 17,
    birthYear: 1955,
    passedAway: null,
    comment: "Book club",
    groups: ["Friend"],
  },
  {
    firstName: "Billy",
    lastName: "Sn.",
    birthMonth: "May",
    birthDay: 22,
    birthYear: 1974,
    passedAway: null,
    comment:
      "A nice guy but not particularly bright - Worried too much about trans stuff and in love with Trump - gross!",
    groups: ["Friend"],
  },
  {
    firstName: "Jesus",
    lastName: "Christ",
    birthMonth: "December",
    birthDay: 25,
    birthYear: 0,
    passedAway: "AD 0033",
    comment: "Who really knows dates when it comes to this mysterious dude?",
    groups: ["Important", "Historical"],
  },
  {
    firstName: "Bugs",
    lastName: "Bunny",
    birthMonth: "April",
    birthDay: 1,
    birthYear: 1938,
    passedAway: "Unknown Year",
    comment: "This happy bastard loves hopping around like a fool",
    groups: ["Cartoon", "Historical"],
  },
  {
    firstName: "TBD",
    lastName: "Mo.",
    birthMonth: "September",
    birthDay: null,
    birthYear: null,
    passedAway: "Unknown Year",
    comment: "XXXXXXX",
    groups: [],
  },
];
